### ISSUE TITLE
Host is on one of our servers and create an rsync one liner to allow for instant downloading of full catalog

### ISSUE THREAD

**Issue by breck7** [breck7/MusicOfAPeople.com#3]
Might be better than git b/c you'd get just the latest files w/o history.

Probably should probably both options.

https://www.reddit.com/r/DataHoarder/comments/yhiyay/comment/iueiji2/?context=3

**Comment by shlokjoshi** [comment]
Ok, I agree, GitHub isn’t the best place for it,

Will look at alternatives, since this will be used with streaming, a CDN might not actually be the worst thing. Let me look into options and we can decide on what to go with.

Sent with a Spark

**Comment by breck7** [comment]
No let's keep GitHub. Let's just add a server too. I can handle that.

**Comment by shlokjoshi** [comment]
I use onrender.com

The demo I first sent was on there, it’s super easy to deploy as well.

You simply connect your GitHub to it, it is free to start.

Sent with a Spark

**Comment by shlokjoshi** [comment]
Any GitHub commits are automatically deployed.

Sent with a Spark

**Comment by breck7** [comment]
onrender.com looks awesome. thanks for bringing it to my attention.

i think it makes sense to do an onrender.com mirror, a github hosted version (the current status quo), and a digital ocean hosted version on our publicDomainCompany.com servers (we like to stick close to the electrons).

i think with those 3 mirrors going (and of course anyone at anytime can clone our repo and create their own mirror), we will have the best reliability and speed of any music site in the world.

**Comment by shlokjoshi** [comment]
Sounds like a plan.

Just got the Mac data transferred out this morning, I’m starting the UI/UX bit for the site and player.

Going through some journey maps and such to build a great listening and using experience for all kinds of visitors on the site, artists, listeners, ad folks if any.

I think the best way to do ads, if any would be a small visual banner, where we dictate format of the ads, this way we can keep it unobtrusive to the listener. Have of course thought of “buymeacoffee” style support buttons. It’ll take me a few days before I can show it to you. Then I’ll go ahead and code it up.

Shared this with a few folks at work, they loved it too!

Peace,
Shlok

**Comment by breck7** [comment]
no ads.
1) sell vinyll records (im looking into buying a record printing company)
2) concert tickets
3) merchandise (https://cottonbureau.com/)
4) ???

but digital should all be 100% free, public domain, open source, ad free.

**Comment by shlokjoshi** [comment]
Ok I hear you,

So just a straight up cut when someone supports an artist through us right?

What about a well designed call to action button to help support artists?

Peace,
Shlok

**Comment by breck7** [comment]
I think we should just provide links to whatever social channel(s) they want to look to (sound cloud, spotify, instagram, snapchat, tiktok, website, etc)

**Comment by shlokjoshi** [comment]
I’ll design this into the next ui mockup as an option. Maybe you’ll like it.

Peace,
Shlok
